### ISSUE TITLE
500 error first time I login

### ISSUE THREAD

**Issue by area** [donsplume/TinStreet-API#1]
[If we're not using this for backend issues, let me know]

If I send a valid login request, I get a 500 error returned the first time. If I repeat the request, it's fine. I assume the trigger is my session invalidating and then logging in again.

**Comment by practual** [comment]
Are you sending cookies with your first request that relate to an existing login session? i.e. how are you identifying the 'first' login attempt?

Just going to leave this here for testing with later:

curl -X POST -d '{"username": "phil", "password": "XXXXXX"}' -b 'user=phil;sid=cf11a5fc-c615-4b72-88ee-c4dd1864251a' -i http://ks370109.kimsufi.com/tinstreet/api/login

HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Sun, 02 Aug 2015 09:33:38 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 112
Connection: keep-alive
Set-Cookie: user=phil; Domain=.ks370109.kimsufi.com; expires=Sun, 02 Aug 2015 10:33:38 GMT; httponly; Path=/
Set-Cookie: sid=45ba6f51-acb5-42e9-83b3-c36eb3c00469; Domain=.ks370109.kimsufi.com; expires=Sun, 02 Aug 2015 10:33:38 GMT; httponly; Path=/
Access-Control-Allow-Origin: http://tinstreet.com:8080
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type

{"sessionId": "45ba6f51-acb5-42e9-83b3-c36eb3c00469", "user": "phil", "expiry": "Sun, 02-Aug-2015 10:33:38 GMT"}

**Comment by area** [comment]
I'm going to guess that I am sending cookies relating to a previously valid, but now expired server-side, session.

**Comment by practual** [comment]
I now suspect that this is actually an error with accessing the database after a long period of inactivity. Tricky to investigate as I don't know what 'long' constitutes at this point.
